language: python
python:
  - "2.7"
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pylint caches; pycodestyle --max-line-length=100 caches; fi
  - py.test caches/test/*